#################################################
###             Default Settings              ###
#################################################

# Application and Active Profile
spring:
  application:
    name: api-gateway
  profiles:
    active: dev
    
zuul:
  prefix: /api/v1
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin, H-APP-Id, Token, APPToken
  semaphore:
    max-semaphores: 500
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 50000
    max-per-route-connections: 5
  routes:
    user:
      path: /user/**
      serviceId: user-service
    se:
      path: /se/**
      serviceId: stock-exchange-service
    sector:
      path: /sector/**
      serviceId: sector-service
    company:
      path: /company/**
      serviceId: company-service
    sp:
      path: /sp/**
      serviceId: stock-price-service
    ipo:
      path: /ipo/**
      serviceId: ipo-service

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 400000
          strategy: THREAD

ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  # MaxTotalHttpConnections: 2000
  # MaxConnectionsPerHost: 1000


#################################################
###             Profile Settings              ###
#################################################

---

### DEV Environement Settings ###
server:
  port: 9000
  
# Spring Application
spring:
  profiles: dev
  
eureka:
  client:
    service-url:
      defaultZone: http://admin:123456@localhost:7000/eureka/

# Logging
logging:
  level:
    ROOT: INFO
    com.ibm.fsd.smc.ms.user: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /logs/apigw-service-dev.log
  
      